// file: TicTacToeOntologyOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package org.asSchool.ttt.dataModel.ontology;

import jade.content.onto.*;
import jade.content.schema.*;
import jade.util.leap.HashMap;
import jade.content.lang.Codec;
import jade.core.CaseInsensitiveString;

/** file: TicTacToeOntologyOntology.java
 * @author ontology bean generator
 * @version 2022/06/20, 20:33:52
 */
public class TicTacToeOntologyOntology extends jade.content.onto.Ontology  {
  //NAME
  public static final String ONTOLOGY_NAME = "TicTacToeOntology";
  // The singleton instance of this ontology
  private static ReflectiveIntrospector introspect = new ReflectiveIntrospector();
  private static Ontology theInstance = new TicTacToeOntologyOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String REGISTERINTERACTION_AGENTPLAYER="agentPlayer";
    public static final String REGISTERINTERACTION="RegisterInteraction";
    public static final String GAMEFIELDINTERACTION_GAMEID="gameID";
    public static final String GAMEFIELDINTERACTION_GAMEBOARD="gameBoard";
    public static final String GAMEFIELDINTERACTION="GameFieldInteraction";
    public static final String REGISTERANSWER_MARK="mark";
    public static final String REGISTERANSWER="RegisterAnswer";
    public static final String GAMERESULTINTERACTION_GAMERESULT="gameResult";
    public static final String GAMERESULTINTERACTION="GameResultInteraction";
    public static final String PUTGAMEFIELD="PutGameField";
    public static final String GETGAMEFIELD="GetGameField";
    public static final String REGISTER="Register";
    public static final String CIRCLE="Circle";
    public static final String AGENTPLAYER="AgentPlayer";
    public static final String GAMEROW_COLUMN3="column3";
    public static final String GAMEROW_COLUMN2="column2";
    public static final String GAMEROW_COLUMN1="column1";
    public static final String GAMEROW="GameRow";
    public static final String CROSS="Cross";
    public static final String ABSTRACTMARKTYPE="AbstractMarkType";
    public static final String GAME_XMARKPLAYER="xMarkPlayer";
    public static final String GAME_GAMEBOARD="gameBoard";
    public static final String GAME_GAMEMOVEHISTORY="gameMoveHistory";
    public static final String GAME_OMARKPLAYER="oMarkPlayer";
    public static final String GAME="Game";
    public static final String GAMEBOARD_GAMEROW1="gameRow1";
    public static final String GAMEBOARD_GAMEROW2="gameRow2";
    public static final String GAMEBOARD_GAMEROW3="gameRow3";
    public static final String GAMEBOARD="GameBoard";
    public static final String HUMANPLAYER="HumanPlayer";
    public static final String GAMEMOVE_GAMEID="gameID";
    public static final String GAMEMOVE_GAMEROW="gameRow";
    public static final String GAMEMOVE_GAMECOLUMN="gameColumn";
    public static final String GAMEMOVE_MARKTYPE="markType";
    public static final String GAMEMOVE="GameMove";
    public static final String ABSTRACTGAMECONCEPTS_GAMEID="gameID";
    public static final String ABSTRACTGAMECONCEPTS="AbstractGameConcepts";
    public static final String ABSTRACTPLAYER_AID="aid";
    public static final String ABSTRACTPLAYER_SCORE="score";
    public static final String ABSTRACTPLAYER_MARKTYPE="markType";
    public static final String ABSTRACTPLAYER="AbstractPlayer";
    public static final String GAMERESULT_REMISPLAYER1="remisPlayer1";
    public static final String GAMERESULT_WINNER="winner";
    public static final String GAMERESULT_LOSER="loser";
    public static final String GAMERESULT_REMISPLAYER2="remisPlayer2";
    public static final String GAMERESULT="GameResult";
    public static final String GAMELIST_GAMELIST="gameList";
    public static final String GAMELIST="GameList";

  /**
   * Constructor
  */
  private TicTacToeOntologyOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema gameListSchema = new ConceptSchema(GAMELIST);
    add(gameListSchema, org.asSchool.ttt.dataModel.ontology.GameList.class);
    ConceptSchema gameResultSchema = new ConceptSchema(GAMERESULT);
    add(gameResultSchema, org.asSchool.ttt.dataModel.ontology.GameResult.class);
    ConceptSchema abstractPlayerSchema = new ConceptSchema(ABSTRACTPLAYER);
    add(abstractPlayerSchema, org.asSchool.ttt.dataModel.ontology.AbstractPlayer.class);
    ConceptSchema abstractGameConceptsSchema = new ConceptSchema(ABSTRACTGAMECONCEPTS);
    add(abstractGameConceptsSchema, org.asSchool.ttt.dataModel.ontology.AbstractGameConcepts.class);
    ConceptSchema gameMoveSchema = new ConceptSchema(GAMEMOVE);
    add(gameMoveSchema, org.asSchool.ttt.dataModel.ontology.GameMove.class);
    ConceptSchema humanPlayerSchema = new ConceptSchema(HUMANPLAYER);
    add(humanPlayerSchema, org.asSchool.ttt.dataModel.ontology.HumanPlayer.class);
    ConceptSchema gameBoardSchema = new ConceptSchema(GAMEBOARD);
    add(gameBoardSchema, org.asSchool.ttt.dataModel.ontology.GameBoard.class);
    ConceptSchema gameSchema = new ConceptSchema(GAME);
    add(gameSchema, org.asSchool.ttt.dataModel.ontology.Game.class);
    ConceptSchema abstractMarkTypeSchema = new ConceptSchema(ABSTRACTMARKTYPE);
    add(abstractMarkTypeSchema, org.asSchool.ttt.dataModel.ontology.AbstractMarkType.class);
    ConceptSchema crossSchema = new ConceptSchema(CROSS);
    add(crossSchema, org.asSchool.ttt.dataModel.ontology.Cross.class);
    ConceptSchema gameRowSchema = new ConceptSchema(GAMEROW);
    add(gameRowSchema, org.asSchool.ttt.dataModel.ontology.GameRow.class);
    ConceptSchema agentPlayerSchema = new ConceptSchema(AGENTPLAYER);
    add(agentPlayerSchema, org.asSchool.ttt.dataModel.ontology.AgentPlayer.class);
    ConceptSchema circleSchema = new ConceptSchema(CIRCLE);
    add(circleSchema, org.asSchool.ttt.dataModel.ontology.Circle.class);

    // adding AgentAction(s)
    AgentActionSchema registerSchema = new AgentActionSchema(REGISTER);
    add(registerSchema, org.asSchool.ttt.dataModel.ontology.Register.class);
    AgentActionSchema getGameFieldSchema = new AgentActionSchema(GETGAMEFIELD);
    add(getGameFieldSchema, org.asSchool.ttt.dataModel.ontology.GetGameField.class);
    AgentActionSchema putGameFieldSchema = new AgentActionSchema(PUTGAMEFIELD);
    add(putGameFieldSchema, org.asSchool.ttt.dataModel.ontology.PutGameField.class);
    AgentActionSchema gameResultInteractionSchema = new AgentActionSchema(GAMERESULTINTERACTION);
    add(gameResultInteractionSchema, org.asSchool.ttt.dataModel.ontology.GameResultInteraction.class);
    AgentActionSchema registerAnswerSchema = new AgentActionSchema(REGISTERANSWER);
    add(registerAnswerSchema, org.asSchool.ttt.dataModel.ontology.RegisterAnswer.class);
    AgentActionSchema gameFieldInteractionSchema = new AgentActionSchema(GAMEFIELDINTERACTION);
    add(gameFieldInteractionSchema, org.asSchool.ttt.dataModel.ontology.GameFieldInteraction.class);
    AgentActionSchema registerInteractionSchema = new AgentActionSchema(REGISTERINTERACTION);
    add(registerInteractionSchema, org.asSchool.ttt.dataModel.ontology.RegisterInteraction.class);

    // adding AID(s)

    // adding Predicate(s)


    // adding fields
    gameListSchema.add(GAMELIST_GAMELIST, abstractGameConceptsSchema, 0, ObjectSchema.UNLIMITED);
    gameResultSchema.add(GAMERESULT_REMISPLAYER2, abstractPlayerSchema, ObjectSchema.OPTIONAL);
    gameResultSchema.add(GAMERESULT_LOSER, abstractPlayerSchema, ObjectSchema.OPTIONAL);
    gameResultSchema.add(GAMERESULT_WINNER, abstractPlayerSchema, ObjectSchema.OPTIONAL);
    gameResultSchema.add(GAMERESULT_REMISPLAYER1, abstractPlayerSchema, ObjectSchema.OPTIONAL);
    abstractPlayerSchema.add(ABSTRACTPLAYER_MARKTYPE, abstractMarkTypeSchema, ObjectSchema.OPTIONAL);
    abstractPlayerSchema.add(ABSTRACTPLAYER_SCORE, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.OPTIONAL);
    abstractPlayerSchema.add(ABSTRACTPLAYER_AID, (ConceptSchema)getSchema(BasicOntology.AID), ObjectSchema.OPTIONAL);
    abstractGameConceptsSchema.add(ABSTRACTGAMECONCEPTS_GAMEID, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.OPTIONAL);
    gameMoveSchema.add(GAMEMOVE_MARKTYPE, abstractMarkTypeSchema, ObjectSchema.OPTIONAL);
    gameMoveSchema.add(GAMEMOVE_GAMECOLUMN, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.OPTIONAL);
    gameMoveSchema.add(GAMEMOVE_GAMEROW, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.OPTIONAL);
    gameMoveSchema.add(GAMEMOVE_GAMEID, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.OPTIONAL);
    gameBoardSchema.add(GAMEBOARD_GAMEROW3, gameRowSchema, ObjectSchema.OPTIONAL);
    gameBoardSchema.add(GAMEBOARD_GAMEROW2, gameRowSchema, ObjectSchema.OPTIONAL);
    gameBoardSchema.add(GAMEBOARD_GAMEROW1, gameRowSchema, ObjectSchema.OPTIONAL);
    gameSchema.add(GAME_OMARKPLAYER, abstractPlayerSchema, ObjectSchema.OPTIONAL);
    gameSchema.add(GAME_GAMEMOVEHISTORY, gameMoveSchema, 0, ObjectSchema.UNLIMITED);
    gameSchema.add(GAME_GAMEBOARD, gameBoardSchema, ObjectSchema.OPTIONAL);
    gameSchema.add(GAME_XMARKPLAYER, abstractPlayerSchema, ObjectSchema.OPTIONAL);
    gameRowSchema.add(GAMEROW_COLUMN1, abstractMarkTypeSchema, ObjectSchema.OPTIONAL);
    gameRowSchema.add(GAMEROW_COLUMN2, abstractMarkTypeSchema, ObjectSchema.OPTIONAL);
    gameRowSchema.add(GAMEROW_COLUMN3, abstractMarkTypeSchema, ObjectSchema.OPTIONAL);
    gameResultInteractionSchema.add(GAMERESULTINTERACTION_GAMERESULT, gameResultSchema, ObjectSchema.OPTIONAL);
    registerAnswerSchema.add(REGISTERANSWER_MARK, abstractMarkTypeSchema, ObjectSchema.OPTIONAL);
    gameFieldInteractionSchema.add(GAMEFIELDINTERACTION_GAMEBOARD, gameBoardSchema, ObjectSchema.OPTIONAL);
    gameFieldInteractionSchema.add(GAMEFIELDINTERACTION_GAMEID, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.OPTIONAL);
    registerInteractionSchema.add(REGISTERINTERACTION_AGENTPLAYER, agentPlayerSchema, ObjectSchema.OPTIONAL);

    // adding name mappings

    // adding inheritance
    gameResultSchema.addSuperSchema(abstractGameConceptsSchema);
    humanPlayerSchema.addSuperSchema(abstractPlayerSchema);
    gameSchema.addSuperSchema(abstractGameConceptsSchema);
    crossSchema.addSuperSchema(abstractMarkTypeSchema);
    agentPlayerSchema.addSuperSchema(abstractPlayerSchema);
    circleSchema.addSuperSchema(abstractMarkTypeSchema);
    registerSchema.addSuperSchema(registerInteractionSchema);
    getGameFieldSchema.addSuperSchema(gameFieldInteractionSchema);
    putGameFieldSchema.addSuperSchema(gameFieldInteractionSchema);
    registerAnswerSchema.addSuperSchema(registerInteractionSchema);

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
  }
